# borrowed from: https://github.com/0h-n0/myflet
# and https://trstringer.com/github-actions-create-release-upload-artifacts/

name: Build and create release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install requirements
      run: pip install -r requirements.txt
    - name: run PyInstaller
      run: pwsh ./build.ps1
    - name: run WiX Toolset
      run: pwsh ./build_wix.ps1
    # I think this just uploads the artifact to the workflow run 
    - name: save artifact
      uses: actions/upload-artifact@v3
      with:
        name: "Windows Installer"
        path: ./wix/pdf_rotate_installer.msi
    - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "TODO: ${{ steps.version.outputs.version }}"
          tag_name: "TODO:${{ github.ref }}"
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
    - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./wix/pdf_rotate_installer.msi
          asset_name: pdf_rotate_installer.msi
          asset_content_type: application/octet-stream    
    
